language: java

jdk:
  - oraclejdk7

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

notifications:
  email: false

# cache between builds
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
